name: deploy

on:
  push:
    branches: [ "main" ]
  
jobs:
  deploy:

    runs-on: ubuntu-latest

    

    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t praveenyadav1107/next-js-app
    - run: echo "${{secrets.DOCKERHUB_SECRET}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    - run: docker push praveenyadav1107/next-js-app:latest